# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='math.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nmath.proto\".\n\x0bMathRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\t\n\x01z\x18\x03 \x01(\t\"/\n\x0cMathResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t20\n\x04Math\x12(\n\tOrderMath\x12\x0c.MathRequest\x1a\r.MathResponseb\x06proto3'
)




_MATHREQUEST = _descriptor.Descriptor(
  name='MathRequest',
  full_name='MathRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='MathRequest.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='MathRequest.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='MathRequest.z', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=60,
)


_MATHRESPONSE = _descriptor.Descriptor(
  name='MathResponse',
  full_name='MathResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='MathResponse.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='MathResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['MathRequest'] = _MATHREQUEST
DESCRIPTOR.message_types_by_name['MathResponse'] = _MATHRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MathRequest = _reflection.GeneratedProtocolMessageType('MathRequest', (_message.Message,), {
  'DESCRIPTOR' : _MATHREQUEST,
  '__module__' : 'math_pb2'
  # @@protoc_insertion_point(class_scope:MathRequest)
  })
_sym_db.RegisterMessage(MathRequest)

MathResponse = _reflection.GeneratedProtocolMessageType('MathResponse', (_message.Message,), {
  'DESCRIPTOR' : _MATHRESPONSE,
  '__module__' : 'math_pb2'
  # @@protoc_insertion_point(class_scope:MathResponse)
  })
_sym_db.RegisterMessage(MathResponse)



_MATH = _descriptor.ServiceDescriptor(
  name='Math',
  full_name='Math',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=111,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='OrderMath',
    full_name='Math.OrderMath',
    index=0,
    containing_service=None,
    input_type=_MATHREQUEST,
    output_type=_MATHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MATH)

DESCRIPTOR.services_by_name['Math'] = _MATH

# @@protoc_insertion_point(module_scope)
